# Generated by Django 2.2.1 on 2019-08-06 23:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListaDeseos',
            fields=[
                ('lista_deseos_id', models.AutoField(primary_key=True, serialize=False)),
                ('cart_id', models.TextField()),
                ('book_id', models.IntegerField()),
                ('added_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListaRenta',
            fields=[
                ('lista_rentados_id', models.AutoField(primary_key=True, serialize=False)),
                ('cart_id', models.TextField()),
                ('book_id', models.IntegerField()),
                ('added_on', models.DateField(blank=True, default=datetime.date(2019, 8, 6))),
                ('deleted_on', models.DateField(blank=True, default=datetime.date(2019, 8, 16))),
            ],
        ),
    ]
