# Generated by Django 2.2.1 on 2019-08-06 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0003_auto_20190804_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listarenta',
            name='added_on',
            field=models.DateField(blank=True, default=datetime.date(2019, 8, 6)),
        ),
        migrations.AlterField(
            model_name='listarenta',
            name='deleted_on',
            field=models.DateField(blank=True, default=datetime.date(2019, 8, 16)),
        ),
    ]
