# Generated by Django 2.2.1 on 2019-07-26 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autors',
            name='description',
        ),
    ]
